// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fm_create_param
SEXP fm_create_param(float learning_rate, int rank, float lambda_w, float lambda_v, const String task);
RcppExport SEXP FM_fm_create_param(SEXP learning_rateSEXP, SEXP rankSEXP, SEXP lambda_wSEXP, SEXP lambda_vSEXP, SEXP taskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< float >::type lambda_w(lambda_wSEXP);
    Rcpp::traits::input_parameter< float >::type lambda_v(lambda_vSEXP);
    Rcpp::traits::input_parameter< const String >::type task(taskSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_create_param(learning_rate, rank, lambda_w, lambda_v, task));
    return rcpp_result_gen;
END_RCPP
}
// fm_init_weights
void fm_init_weights(SEXP ptr, const NumericVector& w_R, const NumericMatrix& v_R);
RcppExport SEXP FM_fm_init_weights(SEXP ptrSEXP, SEXP w_RSEXP, SEXP v_RSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type w_R(w_RSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_R(v_RSEXP);
    fm_init_weights(ptr, w_R, v_R);
    return R_NilValue;
END_RCPP
}
// fm_partial_fit
NumericVector fm_partial_fit(SEXP ptr, const S4& X, const NumericVector& y, int nthread, int do_update);
RcppExport SEXP FM_fm_partial_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP, SEXP nthreadSEXP, SEXP do_updateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const S4& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    Rcpp::traits::input_parameter< int >::type do_update(do_updateSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_partial_fit(ptr, X, y, nthread, do_update));
    return rcpp_result_gen;
END_RCPP
}
// fm_dump
List fm_dump(SEXP ptr);
RcppExport SEXP FM_fm_dump(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_dump(ptr));
    return rcpp_result_gen;
END_RCPP
}
