# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fm_create_param <- function(learning_rate, rank, lambda_w, lambda_v) {
    .Call('FM_fm_create_param', PACKAGE = 'FM', learning_rate, rank, lambda_w, lambda_v)
}

fm_init_weights <- function(ptr, w_R, v_R) {
    invisible(.Call('FM_fm_init_weights', PACKAGE = 'FM', ptr, w_R, v_R))
}

fm_partial_fit <- function(ptr, X, y, nthread = 1L, do_update = 1L) {
    .Call('FM_fm_partial_fit', PACKAGE = 'FM', ptr, X, y, nthread, do_update)
}

fm_dump <- function(ptr) {
    .Call('FM_fm_dump', PACKAGE = 'FM', ptr)
}

