# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fm_create_param <- function(learning_rate, rank, lambda_w, lambda_v, w0_R, w_R, v_R, grad_w2_R, grad_v2_R, task) {
    .Call('_FM_fm_create_param', PACKAGE = 'FM', learning_rate, rank, lambda_w, lambda_v, w0_R, w_R, v_R, grad_w2_R, grad_v2_R, task)
}

fm_create_model <- function(params_ptr) {
    .Call('_FM_fm_create_model', PACKAGE = 'FM', params_ptr)
}

fill_float_matrix_randn <- function(x, stdev = 0.001) {
    invisible(.Call('_FM_fill_float_matrix_randn', PACKAGE = 'FM', x, stdev))
}

fill_float_matrix <- function(x, val) {
    invisible(.Call('_FM_fill_float_matrix', PACKAGE = 'FM', x, val))
}

fill_float_vector_randn <- function(x, stdev = 0.001) {
    invisible(.Call('_FM_fill_float_vector_randn', PACKAGE = 'FM', x, stdev))
}

fill_float_vector <- function(x, val) {
    invisible(.Call('_FM_fill_float_vector', PACKAGE = 'FM', x, val))
}

fm_partial_fit <- function(ptr, X, y, w, nthread = 1L, do_update = 1L) {
    .Call('_FM_fm_partial_fit', PACKAGE = 'FM', ptr, X, y, w, nthread, do_update)
}

is_invalid_ptr <- function(sexp_ptr) {
    .Call('_FM_is_invalid_ptr', PACKAGE = 'FM', sexp_ptr)
}

